"use client";

import StyledComponentsRegistry from "./registry";

import MyThemeProvider from "../styles/MyThemeProvider";
import HomePage from './page';

const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <MyThemeProvider>
            <HomePage />
          </MyThemeProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
