"use client";

import StyledComponentsRegistry from "./registry";
import styled from "styled-components";

const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const Body = styled.body`
  margin: 0;
  padding: 0;
  * {
    box-sizing: border-box;
  }
`;

const Container = styled.div`
  background-color: darkgray;
  height: 100vh;
  color: white;
`;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Body>
        <StyledComponentsRegistry>
          <Container>{children}</Container>
        </StyledComponentsRegistry>
      </Body>
    </html>
  );
}
